=== GreatWizard/keycap-archivist-database/src/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "array",
  "title": "The Root Schema",
  "description": "The root schema comprises the entire JSON document.",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "description": "An explanation about the purpose of this instance.",
    "default": {},
    "examples": [
      {
        "name": "Alpha Keycaps",
        "instagram": "https://www.instagram.com/alphakeycaps/",
        "id": "a00953bd",
        "sculpts": [
          {
            "id": "cf2fecc9",
            "colorways": [
              {
                "img": "https://images.squarespace-cdn.com/content/v1/5ba3cec929f2cc0d91dbe9b2/1551885204908-NDQFFGI50EPMISWLMTZF/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/DSC00153.jpg",
                "id": "86be2a4f",
                "name": "Baba Yaga Keypora"
              }
            ],
            "name": "keypora"
          }
        ],
        "website": "https://alphakeycaps.com",
        "discord": "https://discord.com/invite/eBVaYwn"
      }
    ],
    "required": ["id", "name", "sculpts"],
    "properties": {
      "id": {
        "$id": "#/items/properties/id",
        "type": "string",
        "title": "The Id Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": ["a00953bd"]
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": ["Alpha Keycaps"]
      },
      "instagram": {
        "$id": "#/items/properties/instagram",
        "type": "string",
        "title": "The Instagram Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": ["https://www.instagram.com/alphakeycaps/"]
      },
      "website": {
        "$id": "#/items/properties/website",
        "type": "string",
        "title": "The Website Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": ["https://alphakeycaps.com"]
      },
      "discord": {
        "$id": "#/items/properties/discord",
        "type": "string",
        "title": "The Discord Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": ["https://discord.com/invite/eBVaYwn"]
      },
      "sculpts": {
        "$id": "#/items/properties/sculpts",
        "type": "array",
        "title": "The Sculpts Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": [],
        "items": {
          "$id": "#/items/properties/sculpts/items",
          "type": "object",
          "title": "The Items Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": {},
          "examples": [
            {
              "id": "cf2fecc9",
              "colorways": [
                {
                  "name": "Baba Yaga Keypora",
                  "img": "https://images.squarespace-cdn.com/content/v1/5ba3cec929f2cc0d91dbe9b2/1551885204908-NDQFFGI50EPMISWLMTZF/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/DSC00153.jpg",
                  "id": "86be2a4f"
                }
              ],
              "name": "keypora"
            }
          ],
          "required": ["id", "name", "colorways"],
          "properties": {
            "id": {
              "$id": "#/items/properties/sculpts/items/properties/id",
              "type": "string",
              "title": "The Id Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": ["cf2fecc9"]
            },
            "name": {
              "$id": "#/items/properties/sculpts/items/properties/name",
              "type": "string",
              "title": "The Name Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": ["keypora"]
            },
            "colorways": {
              "$id": "#/items/properties/sculpts/items/properties/colorways",
              "type": "array",
              "title": "The Colorways Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": [],
              "items": {
                "$id": "#/items/properties/sculpts/items/properties/colorways/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": {},
                "examples": [
                  {
                    "img": "https://images.squarespace-cdn.com/content/v1/5ba3cec929f2cc0d91dbe9b2/1551885204908-NDQFFGI50EPMISWLMTZF/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/DSC00153.jpg",
                    "id": "86be2a4f",
                    "name": "Baba Yaga Keypora"
                  }
                ],
                "required": ["name", "img", "id"],
                "properties": {
                  "name": {
                    "$id": "#/items/properties/sculpts/items/properties/colorways/items/properties/name",
                    "type": "string",
                    "title": "The Name Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": ["Baba Yaga Keypora"]
                  },
                  "img": {
                    "$id": "#/items/properties/sculpts/items/properties/colorways/items/properties/img",
                    "type": "string",
                    "title": "The Img Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                      "https://images.squarespace-cdn.com/content/v1/5ba3cec929f2cc0d91dbe9b2/1551885204908-NDQFFGI50EPMISWLMTZF/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/DSC00153.jpg"
                    ]
                  },
                  "id": {
                    "$id": "#/items/properties/sculpts/items/properties/colorways/items/properties/id",
                    "type": "string",
                    "title": "The Id Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": ["86be2a4f"]
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== GreatWizard/keycap-archivist-database/db/backward-caps.json
{"id":"634ef7c","name":"Backward Caps","instagram":"https://www.instagram.com/backward.caps.sales/","website":"","sculpts":[{"id":"4a11f621","name":"RMF","colorways":[{"name":"Tru No Face","img":"https://lh3.googleusercontent.com/7oiAoVBM447v8oB5q7uONGEtkKpwzZsJqWkGDxr9FVyjiXfEKdgqVJ8w7vDKBCETTW5gnYk_MLv5CM5G_tc3BESid6Tu51jlHUNalrrhfUfdlbVfTFJkD_dXcbqNVhuQzg","id":"36614b7b"},{"name":"Raspberry Herpes","img":"https://lh3.googleusercontent.com/rEYjnKFyk90Q3IciCs4VFtaAosIQUjNaAAJVNpdEKpyrECTQ1ni3yopRiX1Gs-ffVHc6YTBsZcqBTYs7et2eeCmvUpQ99Bb6Qb8CAMx_yu1mJ9usCJMCre9keV7yoGEKrA","id":"948a0573"},{"name":"Santa’s sack","img":"https://lh3.googleusercontent.com/jHbyUFdYk-52evQGJFkWZ9va2G5d6kDuH773mBcx6LiJ8UZr9SxweH4HsWHNzDtMvajr7boit6WPuh2hB3Q8i14FvFs5oTDSpFMwKXiKfQOSYFyqlLoyjhLCWakD_ptDHg","id":"495324ed"},{"name":"Spray Tan","img":"https://lh3.googleusercontent.com/6Zgr32fUXesR-6sV2oyexrR7RPhJZXRegFJqz_3qhDlarSTE2B-aCOmp-g8aCXDsJOe3k7_RI62PACiqSfFEjH7Z0sNt3-m0TM16386aKXLhWvp6mmUYmfbeYFMi1-B5Yg","id":"60447d00"},{"name":"Miami Sunny Side","img":"https://lh6.googleusercontent.com/ANNKi2T79YiABvjWV5H_D96VAftgzzblxHD51jMke__eX_5lD5DwjVVzB-yyh8SPagGSy-rQl-J-xzOPCGlH7Z240nmq-4-hilEt4UTyYcio6TQ_sa4Vy1xG8UcctT3D1g","id":"bfd64340"},{"name":"In The Black","img":"https://lh6.googleusercontent.com/N8fwW7SU0n4BsMUC_y4l-LxR7EvNrVUgpLCQ2nMSULNcmOIdmhVjv6y1QaeiHWDOY2Ae-HBOi67WsuEYg9bKSqLxHA5JL6mqG3ehKbYRo7IezTQYb-93U4LsxYEoMbiCdA","id":"8bd5d5c"},{"name":"Pink Meh-lonade","img":"https://lh6.googleusercontent.com/0H4DUZVx7AU5b7sPdZf1DaKDB3jEq6oW8JtKJe0nYn5Dfm6qq_JVDA8cxudkF--nJ7rT5obn-gldmOZY4sOd3VgYltMgV6s7OiGpXdpVUKAZzMJLLO-8t6uIhoJz9_jIHQ","id":"dada457b"},{"name":"Hyper Oops","img":"https://lh5.googleusercontent.com/KBetZlg37_5bcaqpwsVwvPMO3WU47T6WvRXE9rz1ConQLhfva7PPGbLDQwa4ZpX_xQhB9qKfLG-4C46j66wKCqvdVOA8VZqOI-546Flh06EzZQarK1kxdAZWziwiqL46HQ","id":"13d4f691"},{"name":"Grape blast","img":"https://lh5.googleusercontent.com/ZLnO4BzV3TYdgTZ-cNTuHf2aeFwMW8mI086BKLTV3cCCoiaw7Etx8AhcJttIeVpSP6AX2btVJNhj7rh8Ywu-Qt_nbegNd2swL8ePeXv_9rDSAclxN7j-p-ecrekw6t_big","id":"7d8640db"},{"name":"Fancy Sauce","img":"https://lh4.googleusercontent.com/f0uV5iomQGiwXwyBjRcx7n6b-kwIV6m_gxd3fqGQAu537r1IuVZmvv4AZcMqvr89LFHvfSKXWPpctEm-SU_hkPj5z_YhYYuvNE7Vz_ZPd5_8sQOlKnMTVmOr44FH6e1FCA","id":"f9ad6fab"},{"name":"E99","img":"https://lh5.googleusercontent.com/_X1V8Lc97bhXtBe-hwfHxcmhMJKU5onTDpM4qHxJo11eeZ0ZhrIa88Gquws6UfEuXzKDvMG46x5h4L4n24Jn_mH9zg2JyyC09IPL0H1zkIT_v5B4r-1Umboov3tR_lE9Rg","id":"e35b1fbd"},{"name":"Christmas Blue","img":"https://lh4.googleusercontent.com/77zhnxQa2YnrBMma6Ai9sZqE7tu1sHnz3KxGrzKgEOIRAkLSvFFGTOyXKdyXpIxnyQZVaUAxBYsPKGXBCiM10TDx3dC2bfl-E9FlcNlKLlCUUW8TtA-snxHviXI1pCjaZg","id":"1a7e9ef9"},{"name":"Bing Bug","img":"https://lh3.googleusercontent.com/RZFeznKUy-QjL5_EhCKx3VDKJF1fmXuxIQ2Vy92XJwBzMeTa-ERHlrpyHDLudkxVzYkZ15yWYU3jD5jZ2NqC06k_SfeHrv5sm7HNaAR4e0fj1JKpLVw6o5UWsnCpxZc0Sg","id":"dbe5e37f"},{"name":"Things Basic White Girls","img":"https://lh6.googleusercontent.com/nxyoBjFoBxKd6DUgIxEf9cJXNz2uXYOmsER5Lok7ccgz22TuuVqOw5dpmu2GF2FTVV1WYwDVpr2qG1Tev4mZ2tCO6tYvEJzy_4Blr2fH_81rOuM-AY7FnIxzfP9YfluLpw","id":"e5d8132d"}]},{"id":"8e2b7398","name":"Oh Face","colorways":[{"name":"Master","img":"https://lh5.googleusercontent.com/By8_OUXxq-_MO_lZ_SSqn0VhVx9c9EoWSvIZo_OB0xiuXuZeha_0JPyrER430sC4QGBItEclPvvaBEiBfm8K6xyBmIaFzWyGEa5L_BaYAH02E6mADly9V1cXy07gg0oZPQ","id":"ae4cc109"},{"name":"A cap named git","img":"https://lh4.googleusercontent.com/Ifn1G3LA5UZGdmma8-zDKlsHdGtg28I1ZQrOyzf4s7qEdCN7tK7yIEPsaxEo30asP86zM9OW6vA15AW9hvO0eeBTi7V_E20ghcbQya6xesE0jX3I4xjBOeIGgv1GXtiCiA","id":"7d814e62"},{"name":"Sanchez Swirl","img":"https://lh6.googleusercontent.com/WDSNNov_0mwgqXprYTXkcdMj41xGV-MrHAMr69tkYh9CDhmbZAximDCuuZ3spEQUSpg7axIkpYtrZkecpNztxUvs8Tg6H10qNH28WrTwc7V6C-xj7gpm1pLplG5KhW_8cw","id":"7c321e9"},{"name":"Goldust","img":"https://lh5.googleusercontent.com/vNJ_lyN4FUT7jvda0LKYSJIaqhIydt77Eq7XKpumiRb-EAGq_DoevBMyK7JQ0tm-HXwMWCko-VHsAILRcq9g6sAeR76MimC53uyqZz6vx-4AXxY0d-MxuQyhGzDPcmIvgw","id":"979d3059"},{"name":"Blue Monday","img":"https://lh3.googleusercontent.com/VpTiU6NvvEI82hHoNYnK9ZISPGuZfZSZnrf_mFpP8vyopYpfSFzCpuAUT6JjRDcRXVIgOJ-h748ObGagMDpBADjGI3XOD_x7NTY7wRv23UWo-VpCcQlv-ZJfG5fU2W7cHg","id":"a77d6a3f"},{"name":"Princess Party","img":"https://lh3.googleusercontent.com/nplIZ0qaIOwKkg43RfNX3CTxq-Z8lz68-HWx5uEhmXAnYjRSpccTNCduadsNvfl0K0EXCc7gyamM9OTcvDKoaFV8mSM3oZc6oabagFvDq2316kfwOJfRhabk-4XaVsUOug","id":"e669f99a"},{"name":"My Corona","img":"https://lh5.googleusercontent.com/g-hQkgjUM2926hEwa3EgzBMBXteeEJyVRXzKEN2CX4qx0Mje81iTf6OqwbQ2k7aJojHsygjn_UGOAUSUtTgvS0l0dUDrhyVFqMAh2WaJLcj5XllByYseK4YJsJkJHo71gg","id":"fb353c93"}]},{"id":"2a93f4e1","name":"Mephisto","colorways":[{"name":"Gilded friar","img":"https://lh3.googleusercontent.com/6VkkVFJgMg422Ab6hP6xjoMBiOke-qnWsiW4v0YFUoOnJQuyHV44Juyr2nYsXHyKdJTFloSnftpb0vOOzSv_xBpqMqCFGQBotyiC8hFHoXfzxnDFU-zLefMdK87Sg8WIQQ","id":"7e38dfcb"}]},{"id":"e4748e66","name":"Lovechild","colorways":[{"name":"PAC Handshake","img":"https://lh5.googleusercontent.com/Ro8ENciJWspxtCfeJyHlRZuJLTYWBJ9rhl5iYa7CUehde3E4tRk2H7iKo5_APJ1rwkr0WNNbuXnUrgEZyIq0SfXfqjI-rHDIwWP4-sDoYadfXTuZPWyZzTnABPoZhLavBg","id":"72b40ec5"},{"name":"Late Stage Capitalism","img":"https://lh5.googleusercontent.com/3lvKp9Brai5P0XCN5i2KYGk_4o1ix1eG_a4x-qh8o5m_TsibmQT4xGbSvg5SRqn2hZVn0Rx4jDHQA2ZMdhM-7fRdyoJ-ymU0ZkA6i6ARjofrlOxaUMRl0OYjv-7rIv-djw","id":"e0e8113e"},{"name":"Mystic Jonger","img":"https://lh4.googleusercontent.com/qknzmgAokxm073qjYvqhM1db6jtr5HfNnCx0ZhljJqqJxbJaOD2V_bBsCiBM85dUpRGAEjB2Vm2cxG_ffh_m6ERDe7IEJLl1G2Ll_chBOHdiG-zDnf6dL0_s-P9qJimJjw","id":"51cf5c29"},{"name":"Trudeau Face","img":"https://lh3.googleusercontent.com/oIeY_xxL7kkHly-aUPgDG-UyGBSwVj8GLY-iWe3pQHaQhF-yPeYwyMXscmuEiQ7rc1D7UIUFdFVN3xAxUpZHSG11dClVzwBoiX2RMkg46TZUyutAt0wDzh6U9dNyS9e2VA","id":"de0b6adc"},{"name":"Un-peachment","img":"https://lh4.googleusercontent.com/yxA15EtdSKXOaRc5TPRZtia2mV8bjGBNnqTj_P9hNyJ8t2MtdW61SitWo9kDj8GgX9nLcrxwY6UJgSMYrNdFNQt-4ryp4rEUst2CRW9kueRVydDsNqKSVwa-J9Om18HgTA","id":"2bb88186"},{"name":"Sibling rivalry","img":"https://lh5.googleusercontent.com/kCasDwEcMN9rpYAsrgW60ci775VeXcFoWBiv5EU-BJ2-X_FpW6bcyUoq3Nip4AT_22xdpcWY9ybjd_S3NFirZRDVDeMftufHCy3ehz8PZujmqtnZLcJmyzQRKDXSjqVJEw","id":"c9fa44b4"},{"name":"KPN","img":"https://lh4.googleusercontent.com/k8M55G8_dbGnf-Yi0yxnuOUjGQ8pR4_YO6YbMX8viGvTzGAJGaApgHfW7DdzW-ps9_6jJ3WA6qeHvbGMnFyrEdIVtGsNmW6WE9xguUzjXUUgYfaT-si2SagHj_B0qPvbJw","id":"4c5451a1"},{"name":"Florida Man","img":"https://lh5.googleusercontent.com/gH1RlJoibG9nHPMKn1MxXeu24nn-vc_hllwG9XLUIL8a5ftLXXsYCXjUgOj1xzFyRj184yXaGMavhi5U7aKjYLm5R2CHLb7jlG-m7Uf0xffhAU2BpNw1j9spLo0uAmkHDw","id":"14e8611"},{"name":"Fall of Rome","img":"https://lh5.googleusercontent.com/ZN2Pc1lJVCOl4w7EL78I8wIbTY-ikGPwJMJO6NNiX0FuiF1PL-dbUMSwDJPSa3dJe7jXyeQXRKEFV2BVI00nLSYIXS2wlfzcv6zcJMe6B0tIAUQbfIJY7XptigxPE1k20Q","id":"ff0fa069"},{"name":"Draven","img":"https://lh6.googleusercontent.com/LhEiOhiyjCp4kVgISBD9uoXyf6rYIyorGu2P9FYyS8CjQJXYKnM9Yhhl212yFyxwe4W3TvsWndgn_798dG3TnkF0QM6M-3v84a72r8ZAPAfovCmuhrvRVOp0UWOobcDnmQ","id":"5cb614b3"},{"name":"Doron’s balls","img":"https://lh4.googleusercontent.com/_SMGAbgE3_BRbEp52tGlO1fvymrK11QtvlNej1KNn4vV4mSK4m69IQFy__5uC83X1At3nZpq8PuqAWlxeng3MAn2TJNxNmhIS92F2ixtr2WsjtlSUyw89_yBpguwvGa5zQ","id":"986b02ef"},{"name":"Boston Cream","img":"https://lh4.googleusercontent.com/pCsyyCXZwoGmchrQxQTizcy1BknhI9rhh9F5MF3h1NT5zyoOngSDwniKmlcgpY1vCpa2kVKilrY7tDGhp9yngXZwQuY8kuLRCPQSBockb1veCxyCEGIsJl4YOjCQK1nbXg","id":"4ecda3c3"},{"name":"Bits and bob","img":"https://lh4.googleusercontent.com/-cy8aY3WrtOZAHUYTpz5AhHcON6c2zAKH0mRShLCH5JGIMixBUKXqCnJunufcxYTEJd2qofhWERIOrByK_aFeMyezCXy_8CIpmZ77MRRE5eBdL1_a9WjbKPrVKe_zugJ-g","id":"1b9b45cd"}]}]}

=== GreatWizard/keycap-archivist-database/db/c.y.o-keycaps.json
{"id":"384b501d","name":"C.Y.O Keycaps","instagram":"https://www.instagram.com/ttylerdurden/","website":"","sculpts":[{"id":"2c7a2015","name":"amBEARssador V3","colorways":[{"name":"9009","img":"https://lh4.googleusercontent.com/qMXl3jzIaP0oHQD4EQ6luUDCWrPqMidckEVEKQfoZxdNcwDF34Dk_ZqANNfULgNgYNnxqbwQBFZH1R-c9Qp1OCLoagG9DQ1P2eSsHo5Yd9BKZI4pkl_xvvGMmtdzTJXYJQ","id":"e86bc98e"},{"name":"Exosphere","img":"https://lh5.googleusercontent.com/ZSDB-ora5xFv-NugCNgmSxfAXlc95fwjEcvyagB9KvaeGyLigvdpS3Lldm8C9UnRX9I0ZkmrNP_NafIE1WEuGivjPQYZoWpzI-8ONvLucgEuazLjH8QxCmbNEEqFFSGjqQ","id":"3fb7c5f6"},{"name":"QoD","img":"https://lh5.googleusercontent.com/HQyQV2YBqOsBxJ4DqftCYqDwi89G1nl0UI3QpZinw9ECeufsqHbjnBDn-avxjJZvRzKgzUSojYqDrWOXtwIPH9A3zOT-RM8f2FZlqBebnBEuoCssyh_LopKk0R1AhtdEUg","id":"d335dfeb"},{"name":"Taro","img":"https://lh3.googleusercontent.com/udHCh8eswaMILkl2hqhhA3y3_gbsSWrzqTm9s6q9xyduRuFA8dpQjDHJ3FjmBg4PGh6tZl9tzhDkzCpM_DMAiz8h5XQyIoVJuHwhbYTGtC-sdkKQiY2HM5qQEnkhNML4BQ","id":"9954f5dd"},{"name":"Greyscale","img":"https://lh3.googleusercontent.com/GCs4h2QB1zFAIlyFAGQubm2mrMudHGO_4A3476TsDDylxCyPNHGT7E3HLBzfsyYZ44F5KrsmTb7h-LpzQvQ7OzFF_vzO1P0Lbse4BwsH6daDHgatkY3eNWZYHDVWu8a1Zg","id":"a684de45"}]},{"id":"29cb6513","name":"Packet Pilot V2","colorways":[{"name":"Exosphere","img":"https://lh3.googleusercontent.com/jQt1C_7dNYJgU-Xu60CRk94Kz8fVxwzwilcP49p_nba8q9BRAeT_T94EpXmsKZ9X3HIIIr9PdlTdVzY1y8_ckKUAc6RjtVM_wVmmW4Da7_7KCR3maKRkgGzlIE29px5GQg","id":"6091eb7a"},{"name":"Greyscale","img":"https://lh5.googleusercontent.com/skAYjYSRthZmtfmDddXGPRdzy2xdC5GCHQLhZPMW-tDvAQ5o2LB1J5PkeBcvk-u3xFleK56qedawMVwvGzRHiiC71oPajHvFhYkpBu5CY3j_gvS17IMnqX-YEN9D-NfCkA","id":"abee471d"},{"name":"A cap named git","img":"https://lh5.googleusercontent.com/7pJEshChO70ycXml9kXdbGV1N9M011_htnyitdKuGL2X7PJ1DSfk1cwC7AapHcUR_VMWUDu7ffrBRr6lu3ZXn0d7DKJwRNHJF8Ch5ThwLZAdeoCwa5Mo-eT3NkMydDdeCg","id":"226b4e58"},{"name":"Taro","img":"https://lh4.googleusercontent.com/rwLoA7NiFhXCmBjI_uZE_pgrTZCefEH8xd-LVnXjmZWBxOWKzrnTR9mo_fNTr5fWI9DfR-USY47NNgWPttNRS6NzVuAF1en3y_5XIJ7Kv4nvahhZFh-BUzaMu4Bm99jhhA","id":"f4da1025"}]},{"id":"5e672e81","name":"Bear Claw","colorways":[{"name":"9009","img":"https://lh6.googleusercontent.com/30rLkeoHJzZvKEft4Vtizg75Ddt5y7Cvvn09707qDzntahkt_OC0jIJiFvc8IR5_KU70h1BBosloKqD24s3B5dS0HIJL2Ml6gwzIA6E9PJ3Vwg8s86zfx3dFQTIL3IRdQw","id":"aa6479ae"},{"name":"Taro","img":"https://lh6.googleusercontent.com/E7vO3MG77rAiH6VkgEX08FeuUeaYPeTQvBA1TUwAES5FZ8-DAMfeC0FVONiRWfrau8emM5C47fm7eUSHrzRtqn8C6sywqj3DSU9BeUngAddca3LC1Qs-ZIo2LehT_vQnKQ","id":"a17f72cc"}]},{"id":"2146742e","name":"Blanks","colorways":[{"name":"Taro","img":"https://lh6.googleusercontent.com/byhTxJ1vooOcL4qMLsIUHf95NFnUzgzz4PhF9kGNGCf0_rm7JapdSGovIkFtzsKAVE4s5PmWaAGJRk3i9-sAbINnviK4CFEgNrABPZuIzRjt2XEhnmZxyAMz1vU9NTV-Wg","id":"e4f20e5e"},{"name":"QoD","img":"https://lh6.googleusercontent.com/2-SiqzdUy7gGDWErXj_lhqdDZST4ZBNftPD9xBDCY2osPdGE3uLc-PX33N7FVbFMNmua8y58Hnw-yImuFm01_K2wRaBtKXCR_3FfbpL6-0p2kUOHAHGIOpPSKDPPEUIwDw","id":"830cf491"},{"name":"9009","img":"https://lh3.googleusercontent.com/wCnaXGCI88iGi836IZgswJR_RwTdbolFD18dGyBBbTvyGlhOUO8QtP2KnHAH_DJ4-LjNxODWb1y4vAOsQvCMynRepwt-tltspvX5Vk_NEcHCXDkwExkMpTuRndiiMuSCQQ","id":"ec9481a9"}]}]}
